-   repo: https://github.com/pre-commit/pre-commit-hooks.git
    sha: 003e43251aea1da33f2072f2365ec8b9ceaae070
    hooks:
    -   id: autopep8-wrapper
        language_version: python3.6
    -   id: check-added-large-files
        language_version: python3.6
    -   id: check-docstring-first
        language_version: python3.6
    -   id: check-merge-conflict
        language_version: python3.6
    -   id: check-yaml
        language_version: python3.6
    -   id: debug-statements
        language_version: python3.6
    -   id: detect-private-key
        language_version: python3.6
    -   id: double-quote-string-fixer
        language_version: python3.6
    -   id: end-of-file-fixer
        language_version: python3.6
    -   id: flake8
        language_version: python3.6
    -   id: name-tests-test
        language_version: python3.6
    -   id: requirements-txt-fixer
        language_version: python3.6
    -   id: trailing-whitespace
        language_version: python3.6
-   repo: https://github.com/asottile/reorder_python_imports.git
    sha: 3d86483455ab5bd06cc1069fdd5ac57be5463f10
    hooks:
    -   id: reorder-python-imports
        language_version: python3.6
-   repo: https://github.com/Lucas-C/pre-commit-hooks.git
    sha: 181a63c511691da58116fa19a7241956018660bc
    hooks:
    -   id: remove-tabs
        language_version: python3.6
