version: "3"

services:
  lwaftr:
    build: src/
    privileged: true
    tty: true
    stdin_open: true
    ports:
      - "22"
      - "830"
    environment:
      - LICENSE=license-eval.txt
      - IMAGE=junos-vmx-x86-64-17.3B1.1.qcow2
      - PUBLICKEY=id_rsa.pub
      - CONFIG=lwaftr.conf.txt
    volumes:
      - $PWD:/u:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      net-0:
      net-1:
        ipv4_address: 172.20.1.16
      net-2:
        ipv4_address: 172.20.2.16

  packetblaster:
    build: packetblaster/
    privileged: true
    tty: true
    stdin_open: true
    command: --b4 2001:db8::40,10.10.0.0,1024 --aftr 2001:db8:ffff::100 --count 60000 --rate 0.010 --size 128
    depends_on:
      - lwaftr
    networks:
      net-1:

  b4cpe:
    build: b4cpe/
    privileged: true
    tty: true
    stdin_open: true
    command: 193.5.1.2 1024-2047 fd00:4600::1 fd00:4600:8888::2
    depends_on:
      - lwaftr
    networks:
      net-2:

networks:
  net-0:
  net-1:
    ipam:
      config:
        - subnet: 172.20.1.0/24
  net-2:
    ipam:
      config:
        - subnet: 172.20.2.0/24
